#!/usr/bin/env python3

# || BANDUNG BARAT || JAWA BARAT || INDONESIA ||
# || KECAMATAN || SAGULING || DESA JATI ||
# || DIAN PERMANA || GOMEZ ||

import os
import subprocess

        
def LUNATIX():
    os.system('clear')

def select_menu_display():
    LUNATIX()
    print(f"\033[38;5;197m{' ' * 15}======================================")        
    print(f"\033[38;5;227m{' ' * 20} BACKUP & RESTORE DATA VPS ")
    print(f"\033[38;5;197m{' ' * 15}======================================")    
    print(f"\033[38;5;111m{' ' * 17}1. BACKUP VPS DATA  ")
    print(f"\033[38;5;111m{' ' * 17}2. RESTOR VPS DATA  ")
    print(f"\033[38;5;111m{' ' * 17}3. JADWALKAN BACKUP ")
    print(f"\033[38;5;111m{' ' * 17}x. EXIT")
    print(f"\033[38;5;197m{' ' * 15}====================================== \033[0m")        
    print()

    ltt = input("   Just Input 1-3 or 'x': ")

    if ltt == '1':
        LUNATIX()
        backup_vps()
    elif ltt == '2':
        LUNATIX()
        restor_vps()
    elif ltt == '3':
        LUNATIX()
        autobackup_vps()
    else:
        exit()

                   # Eksekusi script menggunakan subprocess.run
def backup_vps():
    subprocess.run(["backup"])

def restor_vps():
    subprocess.run(["restore"])
    
def autobackup_vps():
    subprocess.run(["jadwal_backup"])    
            
# Main program
if __name__ == "__main__":


    # Tampilkan menu
    select_menu_display()